Agissons
WildCodeSchool/lille-0920-js-p3-favart pull request #10
Opened 2021-01-07 14:24 UTC by Marie-Garde

Je sais il n'y a qu'un seul commit je suis désolée j'ai fait un fausse manip et je me suis planté de branche, pas bien je sais, patapé T.T

2021-01-07 14:43 UTC, Thoms-C submitted a review, later dismissed
despite the 3 prettify in a row, it's of for me !

2021-01-07 15:00 UTC, LoicBrassart commented
Heh, **one** commit but **three** "Prettify", how could I rant about it ? :smirk:

2021-01-07 15:05 UTC, LoicBrassart requested changes
- Remove useless artefacts
- Why renaming `src/components/HeaderBody.jsx` ?

2021-01-07 15:05 UTC, LoicBrassart commented on src/App.js
> +      </Switch>{" "}
Remove useless `{" "}`

2021-01-07 15:09 UTC, Thoms-C approved these changes, later dismissed
changed ok !

2021-01-08 07:40 UTC, LoicBrassart submitted a review, later dismissed
SnE

2021-01-08 13:09 UTC, Thoms-C submitted a review, later dismissed
Ok !

2021-01-11 11:00 UTC, Thoms-C approved these changes
Seems ok !

2021-01-11 11:04 UTC, LoicBrassart approved these changes
SnE

2021-01-11 11:10 UTC, merged