Questionnaire
WildCodeSchool/lille-0920-js-p3-favart pull request #12
Opened 2021-01-11 15:02 UTC by Marie-Garde

2021-01-11 15:38 UTC, Thoms-C submitted a review, later dismissed
i approve this PR !

2021-01-12 12:51 UTC, LoicBrassart requested changes
Nope.

2021-01-12 12:51 UTC, LoicBrassart commented on src/App.js
> +    <Route path="/inscription" component={Inscription} />
**Critical**
Indentation failure -> Netlify was not used -> PR was not read :cry:

2021-01-12 13:05 UTC, Thoms-C approved these changes
Indentation done, nice !

2021-01-12 13:23 UTC, LoicBrassart approved these changes
SnE

2021-01-12 13:23 UTC, LoicBrassart commented on src/styled-components/Inscription.jsx
> +  }
*Advice*
That's not a good idea to add empty blocks.

2021-01-12 15:19 UTC, merged