Action
WildCodeSchool/lille-0920-js-p3-favart pull request #13
Opened 2021-01-18 10:58 UTC by Gauthier-Lhomme

2021-01-18 14:35 UTC, Thoms-C approved these changes, later dismissed
Nice one !

2021-01-19 12:08 UTC, LoicBrassart requested changes
- Useless to add licence files for every font
- The `Fonts` folder should be named `fonts`
- Some alts to change

2021-01-19 12:08 UTC, LoicBrassart commented on src/components/ActionPage.jsx
> +          <ImgContainer src={geffroy} alt="#" />
Add a *meaningful* value to the `alt` attribute ("Mr Geffroy", for example): it should describe the content of your picture

2021-01-19 12:08 UTC, LoicBrassart commented on src/components/ActionPage.jsx
> +          <ImgContainer src={marsac} alt="#" />
Add a meaningful value to the alt attribute ("Mr Marsac", for example): it should describe the content of your picture

2021-01-19 14:53 UTC, Thoms-C approved these changes
Noice !

2021-01-21 07:54 UTC, LoicBrassart approved these changes
Much better !

2021-01-21 08:15 UTC, merged