Page inscription
WildCodeSchool/lille-0920-js-p3-favart pull request #17
Opened 2021-01-19 10:37 UTC by Marie-Garde

2021-01-19 11:00 UTC, Gauthier-Lhomme approved these changes, later dismissed

2021-01-19 15:21 UTC, Thoms-C submitted a review, later dismissed
Ok!

2021-01-21 08:10 UTC, LoicBrassart commented
Please solve conflicts before assigning me ;-)

2021-01-21 08:26 UTC, LoicBrassart requested changes
Some fixes to do

2021-01-21 08:26 UTC, LoicBrassart commented on src/components/Connection.jsx
> +            Pas encore de compte ?{" "}
Remove {" "}

2021-01-21 08:26 UTC, LoicBrassart commented on src/styled-components/Connection.jsx
> +//questionnaire
Comments should be in English

2021-01-21 08:26 UTC, LoicBrassart commented on src/styled-components/SignUp.jsx
> +//questionnaire
Comments should be in English

2021-01-25 09:21 UTC, Gauthier-Lhomme approved these changes

2021-01-26 10:53 UTC, LoicBrassart approved these changes
NmE

2021-01-27 08:53 UTC, merged