Liaison fb
WildCodeSchool/lille-0920-js-p3-favart pull request #19
Opened 2021-01-20 14:07 UTC by Marie-Garde

2021-01-21 08:22 UTC, Thoms-C submitted a review, later dismissed
Seems ok !!

2021-01-21 08:28 UTC, LoicBrassart commented
Solve conflicts before assigning me plz

2021-01-22 10:16 UTC, Gauthier-Lhomme approved these changes, later dismissed

2021-01-22 13:07 UTC, LoicBrassart requested changes
Some fixes to do !

2021-01-22 13:07 UTC, LoicBrassart commented on .env.sample
> +REACT_APP_DB_HOST=
In a frontend app, you **never** mention databases ! :scream:

2021-01-22 13:07 UTC, LoicBrassart commented on .env.sample
> +BACKEND_PORT=
This, on the other end, seems legit. But the variable name *must* begin with `REACT_APP_` to be recognized :shrug:

2021-01-22 13:07 UTC, LoicBrassart commented on package.json
> +    "axios-hooks": "^2.3.0",
What's this package ?

2021-01-22 13:07 UTC, LoicBrassart commented on src/App.js
> +        <Route path="/BDDFavart" component={Link} />
`<Link>` being a named component from `react-router`, I **really** recommend that you change this name (and once again, why mention the database at all ?)

2021-01-22 13:07 UTC, LoicBrassart commented on src/components/DisplayBDD.jsx
> +                <Card>
IIRC, the `key={id}` prop should be on this line, not on it's infants

2021-01-25 09:17 UTC, Gauthier-Lhomme approved these changes

2021-01-26 12:44 UTC, LoicBrassart approved these changes
NmE

2021-01-26 13:58 UTC, merged