BDD Front components
WildCodeSchool/lille-0920-js-p3-favart pull request #21
Opened 2021-01-26 15:37 UTC by Gauthier-Lhomme

2021-01-26 15:49 UTC, Marie-Garde submitted a review, later dismissed
Let's do this Loic !

2021-01-26 15:52 UTC, Marie-Garde approved these changes, later dismissed
Let's do this Loic !

2021-01-27 07:49 UTC, LoicBrassart commented
Yeah, let's do this !! :triumph: 

(Seriously, what's happening ? :laughing: : )

2021-01-27 07:58 UTC, LoicBrassart requested changes
Just no, too many Evils v_v

2021-01-27 07:58 UTC, LoicBrassart commented on package.json
> +    "emailjs-com": "^2.6.4",
What's this package ?

2021-01-27 07:58 UTC, LoicBrassart commented on src/App.js
> +  console.log(token);
No `console.log`

2021-01-27 07:58 UTC, LoicBrassart commented on src/App.js
>          <Route exact path="/" component={Mainpage} />
Three of your `Routes` take the same path, you'll never load `MainPage`

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/ContactUs.jsx
> +        }
No `console.log`

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/InscriptionSignUp.jsx
> +        console.warn(e);
Nope, still no `console.log`

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/ProfilPage.jsx
> +      console.log(res.data);
Nooooooooooope

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/ProfilPage.jsx
> +          {!loading && (
Use a ternary:
```
{loading ? <p>it's loading</p> : {*monstro-code goez here*}}

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/Sidebar.jsx
> +      console.log(res.data);
Ah ? ... Nope

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/ValidateInfo.jsx
> +    errors.password = "Le mot de passe est trop court (8 charactéres minimums)";
Typo: "caractères"

2021-01-27 07:58 UTC, LoicBrassart commented on src/components/ValidateInfo.jsx
> +  } else if (values.password.lenght < 8) {
Typo (this never works !! :warning: ) : `password.length`

2021-01-27 07:59 UTC, LoicBrassart commented
I'd like to add that I'm sure nobody proofread this PR. 
It's refused because of "basic" errors, and they should have been spotted by anyone really reading the code

2021-01-27 08:19 UTC, Marie-Garde commented on package.json
> +    "emailjs-com": "^2.6.4",
Sending an email

2021-01-27 08:31 UTC, Marie-Garde commented on src/components/ProfilPage.jsx
> +      console.log(res.data);
Sorry T.T

2021-01-27 14:22 UTC, Thoms-C approved these changes, later dismissed
Seems ok to me !

2021-01-28 14:37 UTC, Thoms-C approved these changes, later dismissed
Seems pretty ok

2021-01-28 14:47 UTC, Thoms-C approved these changes
Ok !

2021-01-30 08:59 UTC, LoicBrassart approved these changes
NmE at last!

2021-02-01 08:12 UTC, merged