Update client
WildCodeSchool/lille-0920-js-p3-favart pull request #22
Opened 2021-01-27 11:30 UTC by Marie-Garde

2021-01-27 14:33 UTC, Thoms-C reviewed
console.log =>line 21 => UpdateCLient Page

2021-01-27 15:10 UTC, Thoms-C approved these changes, later dismissed
Noice !

2021-01-30 09:03 UTC, LoicBrassart requested changes
You know I' ll never knowingly let pass a PR containing a `console.*`, right ? So, why do you keep writing them ?

2021-01-30 09:03 UTC, LoicBrassart commented on src/components/ConnexionLogin.jsx
> +        console.warn(e);
No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No.

2021-01-30 09:03 UTC, LoicBrassart commented on src/components/InscriptionSignUp.jsx
> +        console.warn(e);
Nein ? Njet ?

2021-01-30 09:03 UTC, LoicBrassart commented on src/components/UpdateClient.jsx
> +        console.warn(e);
Yada !? Yamete kudasai !!

2021-02-01 09:05 UTC, Thoms-C approved these changes
console.warn() delete ok !

2021-02-01 09:07 UTC, Thoms-C approved these changes
Console.warn() deleted !!!

2021-02-02 08:22 UTC, LoicBrassart approved these changes
No more major Evils

2021-02-02 08:22 UTC, LoicBrassart commented on src/components/ProfilPage.jsx
> +    axios.get("http://localhost:3001/client/9").then((res) => {
This line seems random, it's typically the type of line which will break everything

2021-02-02 08:23 UTC, merged