Connexion header
WildCodeSchool/lille-0920-js-p3-favart pull request #23
Opened 2021-01-27 14:29 UTC by Gauthier-Lhomme

Ternary and route

2021-01-27 14:48 UTC, Thoms-C requested changes
console.log =>line 21 => UpdateCLient Page

2021-01-27 15:11 UTC, Thoms-C submitted a review, later dismissed
Noice !

2021-01-30 09:05 UTC, LoicBrassart requested changes
Nope, won't read the same effing EIGHT HUNDREDS lines over and over.
Get this repo in order, I'll resume proofreading asap

2021-01-30 09:05 UTC, LoicBrassart commented on src/components/ConnexionLogin.jsx
> +        console.warn(e);
%ùµ£#~% !!!

2021-02-01 09:08 UTC, Thoms-C approved these changes
Console.warn deleted ok !

2021-02-02 10:24 UTC, LoicBrassart approved these changes
SnE

2021-02-02 10:24 UTC, LoicBrassart commented on src/components/ConnexionLogin.jsx
> +    axios.post("http://localhost:3001/auth/login", values).then((res) => {
You'll need to variabilize this if you ever want it to work in production

2021-02-02 10:30 UTC, merged