Add document
WildCodeSchool/lille-0920-js-p3-favart pull request #25
Opened 2021-01-29 11:14 UTC by Marie-Garde

2021-01-29 12:53 UTC, Thoms-C submitted a review, later dismissed
Seems ok to me

2021-01-30 09:07 UTC, LoicBrassart requested changes

2021-01-30 09:07 UTC, LoicBrassart commented on src/components/UpdateRessources.jsx
> +        console.warn(e);
Nope

2021-02-01 09:14 UTC, Thoms-C approved these changes
The console.warn has been PURGED !

2021-02-02 10:31 UTC, LoicBrassart approved these changes
NmE

2021-02-02 10:33 UTC, merged