Client page2
WildCodeSchool/lille-0920-js-p3-favart pull request #3
Opened 2021-01-04 09:14 UTC by Marie-Garde

2021-01-04 13:31 UTC, Thoms-C approved these changes, later dismissed
Nice !

2021-01-04 17:26 UTC, LoicBrassart requested changes
One misname but good otherwise

2021-01-04 17:26 UTC, LoicBrassart commented on src/components/ClientPage.jsx
> +  Function,
I'd advise against this component name, but as long as it's working...

2021-01-04 17:26 UTC, LoicBrassart commented on src/components/ClientPage.jsx
> +export default function connexion() {
Rename > "ClientPage"

2021-01-05 13:22 UTC, Thoms-C approved these changes, later dismissed
Seems of for me

2021-01-05 15:20 UTC, LoicBrassart submitted a review, later dismissed
SnE

2021-01-05 17:34 UTC, Thoms-C approved these changes
Clear !

2021-01-06 07:52 UTC, LoicBrassart approved these changes
SnE

2021-01-06 08:16 UTC, merged