Carousel
WildCodeSchool/lille-0920-js-p3-favart pull request #30
Opened 2021-02-02 15:55 UTC by Fx-Colliot

2021-02-08 10:37 UTC, Thoms-C commented on src/components/Logo.jsx
> +              <Testing>
We sould change the name of the styled-components

2021-02-08 10:37 UTC, Thoms-C commented on src/styled-components/FlexProjet.jsx
> +export const Tools = styled.li``;
dead code

2021-02-08 10:37 UTC, Thoms-C commented on src/styled-components/FlexProjet.jsx
> +export const Test = styled.ul`
Rename this styled-components

2021-02-08 10:37 UTC, Thoms-C commented on src/styled-components/header/HeaderBodyStyled.jsx
> +<<<<<<< HEAD
Delete text from merging

2021-02-09 10:22 UTC, Thoms-C submitted a review, later dismissed
Seems ok to me !

2021-02-09 10:33 UTC, Thoms-C submitted a review, later dismissed
Ok!

2021-02-09 14:30 UTC, LoicBrassart requested changes
Minor evils

2021-02-09 14:30 UTC, LoicBrassart commented on debug.log
> +[0126/094543.885:ERROR:directory_reader_win.cc(43)] FindFirstFile: Le chemin d�acc�s sp�cifi� est introuvable. (0x3)
What's this file ?

2021-02-09 14:30 UTC, LoicBrassart commented on src/App.js
> +
Why empty lines ?

2021-02-09 14:30 UTC, LoicBrassart commented on src/components/Logo.jsx
> +      .get("http://localhost:5050/logos/")
localhost -> bad idea

2021-02-09 14:30 UTC, LoicBrassart commented on src/components/ProjetsCards.jsx
> +      .get("http://localhost:5050/projets")
Bad idea

2021-02-09 16:28 UTC, LoicBrassart commented
Well tried @Gauthier-Lhomme , but you still need to fix these evils :p

2021-02-10 09:38 UTC, Thoms-C submitted a review, later dismissed
No more evils

2021-02-10 12:27 UTC, LoicBrassart requested changes
Minor syntax Evil

2021-02-10 12:27 UTC, LoicBrassart commented on src/components/Logo.jsx
> +      .get(`${api.defaults.baseURL}/logos/`)
I may be wrong, but this syntax is lighter and should work:
```
axios.get("/logos/")
```

2021-02-10 12:27 UTC, LoicBrassart commented on src/components/ProjetsCards.jsx
> +      .get(`${api.defaults.baseURL}/projets`)
I may be wrong, but this syntax is lighter and should work:
```
axios.get("/logos/")
```I may be wrong, but this syntax is lighter and should work:
```
axios.get("/logos/")
```

2021-02-10 13:31 UTC, Marie-Garde approved these changes
ok

2021-02-10 13:37 UTC, LoicBrassart approved these changes
SnE

2021-02-10 13:46 UTC, merged